import 'dotenv/config';
import { appConfig } from './app';
const shopifyConfig = {
    api_key: process.env.SHOPIFY_API_KEY,
    api_secret: process.env.SHOPIFY_API_SECRET,
    app_id: process.env.SHOPIFY_APP_ID || process.env.SHOPIFY_API_KEY,
    api_version: process.env.SHOPIFY_API_VERSION,
    api_url: appConfig.url,
    app_slug: process.env.SHOPIFY_APP_SLUG,
    scopes: [
        'read_products',
        'write_products',
        'read_orders',
        'write_orders',
        /* The following scopes are used for storefront api */
        'unauthenticated_read_product_listings',
        'unauthenticated_read_product_inventory',
    ],
    webhooks: [
        {
            address: `${appConfig.webhook_url}/api/webhooks/shops/uninstall`,
            topic: 'app/uninstalled',
        },
        {
            address: `${appConfig.webhook_url}/api/webhooks/shops/update`,
            topic: 'shop/update',
        },
    ],
    black_list: {
        emails: [],
        plans: ['staff'],
        email_domains: [
            'fireapps.io',
            'fireapps.vn',
            'firegroup.io',
            'onecommerce.io',
            'flowio.app',
            'sociahead.io',
            'trueprofit.io',
            'alihunter.io',
            'vify.io',
            'techverest.com',
            'sortecom.com',
            'pagefly.io',
            'avada.io',
            'secomapp.com',
            'boostcommerce.net',
            'bonloyalty.com',
            'globosoftware.net',
            'autoketing.com',
            'arenacommerce.com',
            'teeinblue.com',
            'wizzcommerce.io',
            'shopify.com',
            'dserspro.com',
            'zendrop.com',
            'dropshipman.com',
            'spocket.co',
            'trendsi.com',
            'autods.com',
            'aliorders.io',
            'eprolo.com',
            'syncee.co',
            'dropcommerce.com',
            'etailerhub.com',
            'importify.com',
            'cjdropshipping.com',
            'apphq.co',
            'hiyodel.com',
            'copywriter.so',
            'storeya.com',
            'oddex.ca',
        ],
    },
};
export { shopifyConfig };
